// <auto-generated />
using System;
using ApartmentManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApartmentManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApartmentManagement.Models.Apartment", b =>
                {
                    b.Property<int>("ApartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApartmentId"));

                    b.Property<string>("ApartmentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Area")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ApartmentId");

                    b.HasIndex("BuildingId", "ApartmentCode")
                        .IsUnique();

                    b.ToTable("Apartments");
                });

            modelBuilder.Entity("ApartmentManagement.Models.ApartmentContract", b =>
                {
                    b.Property<int>("ApartmentContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApartmentContractId"));

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<string>("ContractCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContractCodeNormalized")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComputedColumnSql("UPPER(LTRIM(RTRIM([ContractCode])))", true);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DepositAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<decimal>("MonthlyRent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ApartmentContractId");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("ContractCodeNormalized")
                        .IsUnique()
                        .HasDatabaseName("UX_ApartmentContracts_ContractCodeNormalized");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("ApartmentContracts", t =>
                        {
                            t.HasCheckConstraint("CK_ApartmentContracts_ContractCode", "LEN(LTRIM(RTRIM([ContractCode]))) > 0");

                            t.HasCheckConstraint("CK_ApartmentContracts_DateRange", "[EndDate] IS NULL OR [EndDate] >= [StartDate]");

                            t.HasCheckConstraint("CK_ApartmentContracts_DepositAmount", "[DepositAmount] >= 0");

                            t.HasCheckConstraint("CK_ApartmentContracts_MonthlyRent", "[MonthlyRent] > 0");

                            t.HasCheckConstraint("CK_ApartmentContracts_Status", "[Status] IN (N'Draft', N'Active', N'Completed', N'Terminated', N'Cancelled')");
                        });
                });

            modelBuilder.Entity("ApartmentManagement.Models.ApartmentInvoice", b =>
                {
                    b.Property<int>("ApartmentInvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApartmentInvoiceId"));

                    b.Property<decimal>("ApartmentArea")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<int>("BillingMonth")
                        .HasColumnType("int");

                    b.Property<int>("BillingYear")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("IssuedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IssuedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ApartmentInvoiceId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("InvoiceCode")
                        .IsUnique();

                    b.HasIndex("IssuedByUserId");

                    b.HasIndex("ApartmentId", "BillingYear", "BillingMonth")
                        .IsUnique();

                    b.HasIndex("ResidentId", "Status", "BillingYear", "BillingMonth");

                    b.ToTable("ApartmentInvoices", t =>
                        {
                            t.HasCheckConstraint("CK_ApartmentInvoices_Amounts", "[ApartmentArea] > 0 AND [TotalAmount] >= 0");

                            t.HasCheckConstraint("CK_ApartmentInvoices_IssueMetadata", "([Status] = N'Draft' AND [IssuedAtUtc] IS NULL AND [IssuedByUserId] IS NULL) OR ([Status] = N'Issued' AND [IssuedAtUtc] IS NOT NULL AND [IssuedByUserId] IS NOT NULL) OR [Status] = N'Void'");

                            t.HasCheckConstraint("CK_ApartmentInvoices_Period", "[BillingYear] BETWEEN 2000 AND 2200 AND [BillingMonth] BETWEEN 1 AND 12");

                            t.HasCheckConstraint("CK_ApartmentInvoices_Status", "[Status] IN (N'Draft', N'Issued', N'Void')");
                        });
                });

            modelBuilder.Entity("ApartmentManagement.Models.ApartmentInvoiceLine", b =>
                {
                    b.Property<int>("ApartmentInvoiceLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApartmentInvoiceLineId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ApartmentInvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("ChargeType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<decimal?>("CurrentReading")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<decimal?>("PreviousReading")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("RateBreakdown")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("SourceMeterReadingId")
                        .HasColumnType("int");

                    b.Property<int?>("SourceTariffId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("ApartmentInvoiceLineId");

                    b.HasIndex("ApartmentInvoiceId");

                    b.HasIndex("SourceMeterReadingId");

                    b.HasIndex("SourceTariffId");

                    b.ToTable("ApartmentInvoiceLines", t =>
                        {
                            t.HasCheckConstraint("CK_ApartmentInvoiceLines_ChargeType", "[ChargeType] IN (N'Management', N'Electricity', N'Water')");

                            t.HasCheckConstraint("CK_ApartmentInvoiceLines_Readings", "([ChargeType] = N'Management' AND [PreviousReading] IS NULL AND [CurrentReading] IS NULL AND [SourceMeterReadingId] IS NULL) OR ([ChargeType] IN (N'Electricity', N'Water') AND [PreviousReading] IS NOT NULL AND [CurrentReading] IS NOT NULL AND [CurrentReading] >= [PreviousReading] AND [SourceMeterReadingId] IS NOT NULL)");

                            t.HasCheckConstraint("CK_ApartmentInvoiceLines_Values", "[Quantity] >= 0 AND [UnitRate] >= 0 AND [Amount] >= 0");
                        });
                });

            modelBuilder.Entity("ApartmentManagement.Models.ApartmentResident", b =>
                {
                    b.Property<int>("ApartmentResidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApartmentResidentId"));

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MoveInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MoveOutDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int");

                    b.HasKey("ApartmentResidentId");

                    b.HasIndex("ResidentId");

                    b.HasIndex("ApartmentId", "ResidentId")
                        .IsUnique()
                        .HasDatabaseName("UX_ApartmentResidents_ActiveAssignment")
                        .HasFilter("[MoveOutDate] IS NULL");

                    b.ToTable("ApartmentResidents", t =>
                        {
                            t.HasCheckConstraint("CK_ApartmentResidents_MoveOutDate", "[MoveOutDate] IS NULL OR [MoveOutDate] >= [MoveInDate]");
                        });
                });

            modelBuilder.Entity("ApartmentManagement.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ApartmentManagement.Models.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuildingId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BuildingCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BuildingName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfFloors")
                        .HasColumnType("int");

                    b.HasKey("BuildingId");

                    b.HasIndex("BuildingCode")
                        .IsUnique();

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("ApartmentManagement.Models.ContractParty", b =>
                {
                    b.Property<int>("ApartmentContractId")
                        .HasColumnType("int");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("ApartmentContractId", "ResidentId");

                    b.HasIndex("ResidentId");

                    b.ToTable("ContractParties", t =>
                        {
                            t.HasCheckConstraint("CK_ContractParties_Role", "[Role] IN (N'Lessor', N'Lessee')");
                        });
                });

            modelBuilder.Entity("ApartmentManagement.Models.ContractStatusHistory", b =>
                {
                    b.Property<int>("ContractStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractStatusHistoryId"));

                    b.Property<int>("ApartmentContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("ContractStatusHistoryId");

                    b.HasIndex("ApartmentContractId");

                    b.HasIndex("ChangedByUserId");

                    b.ToTable("ContractStatusHistory", t =>
                        {
                            t.HasCheckConstraint("CK_ContractStatusHistory_NewStatus", "[NewStatus] IN (N'Draft', N'Active', N'Completed', N'Terminated', N'Cancelled')");

                            t.HasCheckConstraint("CK_ContractStatusHistory_PreviousStatus", "[PreviousStatus] IS NULL OR [PreviousStatus] IN (N'Draft', N'Active', N'Completed', N'Terminated', N'Cancelled')");
                        });
                });

            modelBuilder.Entity("ApartmentManagement.Models.FeeTariff", b =>
                {
                    b.Property<int>("FeeTariffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeeTariffId"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<string>("ChargeType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<decimal>("MonthlyRatePerSquareMeter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("FeeTariffId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("BuildingId", "ChargeType", "EffectiveFrom")
                        .IsUnique();

                    b.ToTable("FeeTariffs", t =>
                        {
                            t.HasCheckConstraint("CK_FeeTariffs_ChargeType", "[ChargeType] IN (N'Management', N'Electricity', N'Water')");

                            t.HasCheckConstraint("CK_FeeTariffs_DateRange", "[EffectiveTo] IS NULL OR [EffectiveTo] >= [EffectiveFrom]");

                            t.HasCheckConstraint("CK_FeeTariffs_ManagementRate", "[MonthlyRatePerSquareMeter] >= 0");
                        });
                });

            modelBuilder.Entity("ApartmentManagement.Models.FeeTariffTier", b =>
                {
                    b.Property<int>("FeeTariffTierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeeTariffTierId"));

                    b.Property<int>("FeeTariffId")
                        .HasColumnType("int");

                    b.Property<int>("TierOrder")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("UpperConsumption")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("FeeTariffTierId");

                    b.HasIndex("FeeTariffId", "TierOrder")
                        .IsUnique();

                    b.ToTable("FeeTariffTiers", t =>
                        {
                            t.HasCheckConstraint("CK_FeeTariffTiers_Values", "[TierOrder] > 0 AND ([UpperConsumption] IS NULL OR [UpperConsumption] > 0) AND [UnitRate] >= 0");
                        });
                });

            modelBuilder.Entity("ApartmentManagement.Models.IncidentTicket", b =>
                {
                    b.Property<int>("IncidentTicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncidentTicketId"));

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AssignedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedToUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("RatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<string>("ResidentFeedback")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ResidentId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("IncidentTicketId");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("TicketCode")
                        .IsUnique();

                    b.HasIndex("ResidentId", "CreatedAtUtc");

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.ToTable("IncidentTickets", t =>
                        {
                            t.HasCheckConstraint("CK_IncidentTickets_Category", "[Category] IN (N'Electricity', N'Water', N'Elevator', N'CommonArea', N'Other')");

                            t.HasCheckConstraint("CK_IncidentTickets_Feedback", "([Rating] IS NULL AND [ResidentFeedback] IS NULL AND [RatedAtUtc] IS NULL) OR ([Rating] IS NOT NULL AND [RatedAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_IncidentTickets_Rating", "[Rating] IS NULL OR [Rating] BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_IncidentTickets_Status", "[Status] IN (N'Submitted', N'InProgress', N'Completed')");
                        });
                });

            modelBuilder.Entity("ApartmentManagement.Models.IncidentTicketStatusHistory", b =>
                {
                    b.Property<int>("IncidentTicketStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncidentTicketStatusHistoryId"));

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IncidentTicketId")
                        .HasColumnType("int");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("IncidentTicketStatusHistoryId");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("IncidentTicketId");

                    b.ToTable("IncidentTicketStatusHistory", t =>
                        {
                            t.HasCheckConstraint("CK_IncidentTicketStatusHistory_NewStatus", "[NewStatus] IN (N'Submitted', N'InProgress', N'Completed')");

                            t.HasCheckConstraint("CK_IncidentTicketStatusHistory_PreviousStatus", "[PreviousStatus] IS NULL OR [PreviousStatus] IN (N'Submitted', N'InProgress', N'Completed')");
                        });
                });

            modelBuilder.Entity("ApartmentManagement.Models.PaymentTransaction", b =>
                {
                    b.Property<int>("PaymentTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentTransactionId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ApartmentInvoiceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ConfirmedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConfirmedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("PaymentTransactionId");

                    b.HasIndex("ApartmentInvoiceId")
                        .IsUnique();

                    b.HasIndex("ConfirmedByUserId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("PaymentTransactions", t =>
                        {
                            t.HasCheckConstraint("CK_PaymentTransactions_Amount", "[Amount] > 0");

                            t.HasCheckConstraint("CK_PaymentTransactions_Status", "([Status] = N'Pending' AND [ConfirmedAtUtc] IS NULL AND [ConfirmedByUserId] IS NULL) OR ([Status] = N'Confirmed' AND [ConfirmedAtUtc] IS NOT NULL AND [ConfirmedByUserId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ApartmentManagement.Models.Resident", b =>
                {
                    b.Property<int>("ResidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResidentId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CitizenId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmergencyContact")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ResidentId");

                    b.HasIndex("CitizenId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Residents", t =>
                        {
                            t.HasCheckConstraint("CK_Residents_CitizenId_Format", "[CitizenId] NOT LIKE '%[^0-9]%' AND LEN([CitizenId]) IN (9, 12)");

                            t.HasCheckConstraint("CK_Residents_DateOfBirth_Minimum", "[DateOfBirth] IS NULL OR [DateOfBirth] >= '1900-01-01'");
                        });
                });

            modelBuilder.Entity("ApartmentManagement.Models.UtilityMeterReading", b =>
                {
                    b.Property<int>("UtilityMeterReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UtilityMeterReadingId"));

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<int>("BillingMonth")
                        .HasColumnType("int");

                    b.Property<int>("BillingYear")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentReading")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PreviousReading")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("ReadAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecordedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UtilityType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("UtilityMeterReadingId");

                    b.HasIndex("RecordedByUserId");

                    b.HasIndex("ApartmentId", "UtilityType", "BillingYear", "BillingMonth")
                        .IsUnique();

                    b.ToTable("UtilityMeterReadings", t =>
                        {
                            t.HasCheckConstraint("CK_UtilityMeterReadings_Period", "[BillingYear] BETWEEN 2000 AND 2200 AND [BillingMonth] BETWEEN 1 AND 12");

                            t.HasCheckConstraint("CK_UtilityMeterReadings_UtilityType", "[UtilityType] IN (N'Electricity', N'Water')");

                            t.HasCheckConstraint("CK_UtilityMeterReadings_Values", "[PreviousReading] >= 0 AND [CurrentReading] >= [PreviousReading]");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ApartmentManagement.Models.Apartment", b =>
                {
                    b.HasOne("ApartmentManagement.Models.Building", "Building")
                        .WithMany("Apartments")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("ApartmentManagement.Models.ApartmentContract", b =>
                {
                    b.HasOne("ApartmentManagement.Models.Apartment", "Apartment")
                        .WithMany("Contracts")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApartmentManagement.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApartmentManagement.Models.ApplicationUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Apartment");

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("ApartmentManagement.Models.ApartmentInvoice", b =>
                {
                    b.HasOne("ApartmentManagement.Models.Apartment", "Apartment")
                        .WithMany("Invoices")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApartmentManagement.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApartmentManagement.Models.ApplicationUser", "IssuedByUser")
                        .WithMany()
                        .HasForeignKey("IssuedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ApartmentManagement.Models.Resident", "Resident")
                        .WithMany("Invoices")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("CreatedByUser");

                    b.Navigation("IssuedByUser");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("ApartmentManagement.Models.ApartmentInvoiceLine", b =>
                {
                    b.HasOne("ApartmentManagement.Models.ApartmentInvoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("ApartmentInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApartmentManagement.Models.UtilityMeterReading", "SourceMeterReading")
                        .WithMany("InvoiceLines")
                        .HasForeignKey("SourceMeterReadingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ApartmentManagement.Models.FeeTariff", "SourceTariff")
                        .WithMany("InvoiceLines")
                        .HasForeignKey("SourceTariffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Invoice");

                    b.Navigation("SourceMeterReading");

                    b.Navigation("SourceTariff");
                });

            modelBuilder.Entity("ApartmentManagement.Models.ApartmentResident", b =>
                {
                    b.HasOne("ApartmentManagement.Models.Apartment", "Apartment")
                        .WithMany("ApartmentResidents")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApartmentManagement.Models.Resident", "Resident")
                        .WithMany("ApartmentResidents")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("ApartmentManagement.Models.ContractParty", b =>
                {
                    b.HasOne("ApartmentManagement.Models.ApartmentContract", "ApartmentContract")
                        .WithMany("Parties")
                        .HasForeignKey("ApartmentContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApartmentManagement.Models.Resident", "Resident")
                        .WithMany("ContractParties")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApartmentContract");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("ApartmentManagement.Models.ContractStatusHistory", b =>
                {
                    b.HasOne("ApartmentManagement.Models.ApartmentContract", "ApartmentContract")
                        .WithMany("StatusHistory")
                        .HasForeignKey("ApartmentContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApartmentManagement.Models.ApplicationUser", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApartmentContract");

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("ApartmentManagement.Models.FeeTariff", b =>
                {
                    b.HasOne("ApartmentManagement.Models.Building", "Building")
                        .WithMany("FeeTariffs")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApartmentManagement.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("ApartmentManagement.Models.FeeTariffTier", b =>
                {
                    b.HasOne("ApartmentManagement.Models.FeeTariff", "FeeTariff")
                        .WithMany("Tiers")
                        .HasForeignKey("FeeTariffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeeTariff");
                });

            modelBuilder.Entity("ApartmentManagement.Models.IncidentTicket", b =>
                {
                    b.HasOne("ApartmentManagement.Models.Apartment", "Apartment")
                        .WithMany("IncidentTickets")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApartmentManagement.Models.ApplicationUser", "AssignedToUser")
                        .WithMany("AssignedIncidentTickets")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ApartmentManagement.Models.Resident", "Resident")
                        .WithMany("IncidentTickets")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("AssignedToUser");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("ApartmentManagement.Models.IncidentTicketStatusHistory", b =>
                {
                    b.HasOne("ApartmentManagement.Models.ApplicationUser", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApartmentManagement.Models.IncidentTicket", "IncidentTicket")
                        .WithMany("StatusHistory")
                        .HasForeignKey("IncidentTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("IncidentTicket");
                });

            modelBuilder.Entity("ApartmentManagement.Models.PaymentTransaction", b =>
                {
                    b.HasOne("ApartmentManagement.Models.ApartmentInvoice", "Invoice")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("ApartmentInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApartmentManagement.Models.ApplicationUser", "ConfirmedByUser")
                        .WithMany()
                        .HasForeignKey("ConfirmedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ConfirmedByUser");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("ApartmentManagement.Models.Resident", b =>
                {
                    b.HasOne("ApartmentManagement.Models.ApplicationUser", "User")
                        .WithOne("Resident")
                        .HasForeignKey("ApartmentManagement.Models.Resident", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApartmentManagement.Models.UtilityMeterReading", b =>
                {
                    b.HasOne("ApartmentManagement.Models.Apartment", "Apartment")
                        .WithMany("UtilityMeterReadings")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApartmentManagement.Models.ApplicationUser", "RecordedByUser")
                        .WithMany()
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("RecordedByUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ApartmentManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ApartmentManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApartmentManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ApartmentManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApartmentManagement.Models.Apartment", b =>
                {
                    b.Navigation("ApartmentResidents");

                    b.Navigation("Contracts");

                    b.Navigation("IncidentTickets");

                    b.Navigation("Invoices");

                    b.Navigation("UtilityMeterReadings");
                });

            modelBuilder.Entity("ApartmentManagement.Models.ApartmentContract", b =>
                {
                    b.Navigation("Parties");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("ApartmentManagement.Models.ApartmentInvoice", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("PaymentTransactions");
                });

            modelBuilder.Entity("ApartmentManagement.Models.ApplicationUser", b =>
                {
                    b.Navigation("AssignedIncidentTickets");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("ApartmentManagement.Models.Building", b =>
                {
                    b.Navigation("Apartments");

                    b.Navigation("FeeTariffs");
                });

            modelBuilder.Entity("ApartmentManagement.Models.FeeTariff", b =>
                {
                    b.Navigation("InvoiceLines");

                    b.Navigation("Tiers");
                });

            modelBuilder.Entity("ApartmentManagement.Models.IncidentTicket", b =>
                {
                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("ApartmentManagement.Models.Resident", b =>
                {
                    b.Navigation("ApartmentResidents");

                    b.Navigation("ContractParties");

                    b.Navigation("IncidentTickets");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("ApartmentManagement.Models.UtilityMeterReading", b =>
                {
                    b.Navigation("InvoiceLines");
                });
#pragma warning restore 612, 618
        }
    }
}
